{% set version = "3.7.3" %}

package:
  name: bison
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/bison/bison-{{ version }}.tar.gz
  sha256: 104fe912f2212ab4e4a59df888a93b719a046ffc38d178e943f6c54b1f27b3c7

build:
  skip: true  # [win]
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - perl
    - make
    - flex   # [build_platform != target_platform]
  host:
    - flex
    - libiconv # [osx]
  run:
    - flex

test:
  commands:
    - yacc --help   # [unix]
    - bison --help  # [unix]

about:
  home: https://www.gnu.org/software/bison/
  license: GPL-3.0
  license_file: COPYING
  summary: General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.
  description: |
    Bison is a general-purpose parser generator that converts an annotated
    context-free grammar into a deterministic LR or generalized LR (GLR) parser
    employing LALR(1) parser tables.
  dev_url: https://git.savannah.gnu.org/git/bison.git
  doc_url: http://savannah.gnu.org/projects/bison/

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
