{% set version = "3.0.5" %}

package:
  name: bison
  version: {{ version }}

source:
  fn: bison-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/bison/bison-{{ version }}.tar.gz
  md5: 41ad57813157b61bfa47e33067a9d6f0

build:
  skip: true  # [win]
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m4
    - flex
    - perl

test:
  commands:
    - yacc --help   # [unix]
    - bison --help  # [unix]

about:
  home: https://www.gnu.org/software/bison/
  license: GPL 3
  summary: General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
